repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0  # must match test-requirements.txt
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1  # must match test-requirements.txt
    hooks:
      - id: isort
