exclude: '^(mypyc/external/)|(mypy/typeshed/)'  # Exclude all vendored code from lints
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # must match test-requirements.txt
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/psf/black
    rev: 23.3.0  # must match test-requirements.txt
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0  # must match test-requirements.txt
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0  # must match test-requirements.txt
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==23.3.23  # must match test-requirements.txt
          - flake8-noqa==1.3.1       # must match test-requirements.txt

ci:
  # We run flake8 as part of our GitHub Actions suite in CI
  skip: [flake8]
