name: Check documentation build

on:
  push:
    branches: [master, 'release*']
    tags: ['*']
  pull_request:
    paths:
    - 'docs/**'
    - 'mypyc/doc/**'
    - '**/*.rst'
    - '**/*.md'
    - CREDITS
    - LICENSE

jobs:
  docs:
    runs-on: ubuntu-latest
    env:
      TOXENV: docs
      TOX_SKIP_MISSING_INTERPRETERS: False
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install tox
        run: pip install --upgrade 'setuptools!=50' tox==3.24.5
      - name: Setup tox environment
        run: tox -e ${{ env.TOXENV }} --notest
      - name: Test
        run: tox -e ${{ env.TOXENV }} --skip-pkg-install
